#!/bin/bash

# Set the date on programmer jig
# set-date yy-mm-dd

IFS='-'
read -a bar <<< "$1"

F=/tmp/setdate$RANDOM

CHECK=`bc <<EOF
obase=16
ibase=16
100-(04+07+${bar[0]}+${bar[1]}+${bar[2]})%100
EOF
`
echo ":04000700"${bar[2]}"00"${bar[1]}${bar[0]}$CHECK  > $F
echo ":00000001FF" >> $F
avrdude -p m328p -c USBtiny -U eeprom:w:$F:i
rm $F
